web:
  build: .
  env_file: ./env/web.env
  ports:
    - "8000:8000"
  links:
    - redis
  volumes:
    - .:/usr/src/app
  working_dir: /usr/src/app
redis:
  image: redis:3.0.7
  ports:
    - "6379:6379"
